### ISSUE TITLE
DBI_CryptType crypt does not appear to work

### ISSUE THREAD

**Issue by esabol** [matisse/Apache-AuthCookieDBI#3]
I recently upgraded an old mod_perl application that used mod_perl 1.99xx and Apache::AuthCookieDBI to the latest versions of Apache 2.2.x and mod_perl 2.0.x and Apache2::AuthCookieDBI.

This application used DBI_CryptType crypt. I could not get it working with Apache2::AuthCookieDBI. It always reported that the password was wrong. Looking into the Apache2::AuthCookieDBI code, the `_crypt_digest` method seemed just plain wrong to my eye.
```Perl
sub _crypt_digest {
    my ( $class, $plaintext, $encrypted ) = @_;
    my $salt = substr $encrypted, 0, 2;
    return crypt $plaintext, $salt;
}
```
It's throwing away all but the first two characters of the encrypted password. I think this is a bug. I'm not a security expert, but I'm fairly sure that's not how you're supposed to verify a password with `crypt()`. I don't think you need to extract the salt from the crypted password, nor should you assume how many characters the salt is. Some salts are longer than 2 characters. It depends on how on the password is encrypted. AFAIK, the correct algorithm to use `crypt()` to verify a password is simply
```Perl
   if (crypt( $password, $crypted_password ) eq $crypted_password) {
      # $password is correct
   } else {
      # $password is wrong
   }
````
This is also how Apache::AuthCookieDBI did it. So I changed the `%password_checker` hash in `_check_password()` to be the following instead:
```Perl
    my %password_checker = (
        ...
        'crypt' => sub {
            return crypt( $password, $crypted_password ) eq $crypted_password;
        },
       ...
```
And that fixed the problem. Logins worked again.

Do you agree with this fix? Would you like me to open a PR with that change? Thanks!

**Comment by esabol** [comment]
Also, for reference, `perldoc -f crypt` says this:
```
            When verifying an existing digest string you should use the
            digest as the salt (like "crypt($plain, $digest) eq $digest").
            The SALT used to create the digest is visible as part of the
            digest. This ensures "crypt" will hash the new string with the
            same salt as the digest. This allows your code to work with the
            standard "crypt" and with more exotic implementations. In other
            words, assume nothing about the returned string itself nor about
            how many bytes of SALT may matter.
```

**Comment by matisse** [comment]
I think you are right. Please do open a PR and I will look at it as soon as I can.

**Comment by esabol** [comment]
PR #4 submitted. Thanks for taking a look at it.

**Comment by matisse** [comment]
The uploaded file

   Apache2-AuthCookieDBI-2.18.tar.gz

has entered CPAN as

 file: $CPAN/authors/id/M/MA/MATISSE/Apache2-AuthCookieDBI-2.18.tar.gz
 size: 42223 bytes
  md5: fa3cad0f85ee63d68bf04e1e7f904359
 sha1: 2abc9cd24d161cdd01c8ff42cf180a853965ef3e

CPAN Testers will start reporting results in an hour or so:

 http://matrix.cpantesters.org/?dist=Apache2-AuthCookieDBI

Request entered by: MATISSE (Matisse Enzer)
Request entered on: Sat, 17 Aug 2019 19:41:18 GMT
Request completed:  Sat, 17 Aug 2019 19:41:22 GMT
